name: Weekly DomD Summary

on:
  schedule:
    - cron: '10 6 * * 6'   # sobota 06:10
  workflow_dispatch:

permissions:
  contents: write

jobs:
  weekly_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas

      - name: Run weekly summary script
        run: python domd-weekly-summary.py

      - name: Commit and push weekly summary
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mieszkania_dom_*.csv || true
          git commit -m "Weekly summary $(date +'%Y-%m-%d')" || echo "No new summary to commit"
          git push
